
version: 2

sources:
  - name: staging
    database: real_estate_properties
    schema: development
    tables:
      - name: crimes_summary

models:
  - name: crimes_summary
    description: >
      Summary crime statistics by city and by category of crime (e.g. aggravated assault, burglary etc.) over the last 30, 180 and 365 days.
    columns:
      - name: city
        description: "Name of city"
      - name: category
        description: "Incident crime category"
      - name: gang_related
        description: "Indicates if the crime incident was gang related"
      - name: num_crimes_last30days
        description: "Number of crime incidents in the last 30 days"
      - name: num_crimes_last180days
        description: "Number of crime incidents in the last 180 days"
      - name: num_crimes_lastyear
        description: "Number of crime incidents in the last 365 days"

  - name: weather_summary
    description: >
      Summary weather statistics by zip code and city over the last 30, 180 and 365 days.
    columns:
      - name: zip_code
        description: "Zip code"
      - name: city
        description: "Name of city"
      - name: season
        description: "Winter/Spring/Summer/Fall"
      - name: avg_temperature
        description: "Average daily temperature in Fahrenheit"
      - name: avg_humidity
        description: "Average daily percentage humidity"
      - name: avg_precip_inches
        description: "Average daily precipitation level in inches"

        