services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=weather
    volumes:
      - "./weather_postgres_data:/var/lib/postgresql/data:rw"
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
    ports:
      - "5432:5432"
    networks:
      - airflow
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8081:80"
    networks:
      - airflow

networks:
  airflow:
    external:
      name: airflow_default

  